name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "${internalVersion}"
softdepend: [Spout] #hack to fix trove errors
api-version: 1.13

# Разрешения находятся не тут. Читайте http://wiki.sk89q.com/wiki/WEPIF/DinnerPerms
